version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'mongodb-shopping-app'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ~/mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'